services:
  # db:
  #   image: 'postgres'
  #   environment:
  #     POSTGRES_USER: 'postgres'
  #     POSTGRES_PASSWORD: 'root'
  #     POSTGRES_DB: 'mydatabase'
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - ticketmaster-db-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgadmin'
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    networks:
      - app-network

  # backend:
  #   build:
  #     context: .
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-network

volumes:
  ticketmaster-db-data:

networks:
  app-network:
    driver: bridge